/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/core/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Phase marker confirms which milestone this build is at.
         */
        get: operations["health_api_core_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submissions
         * @description Inbox — triaged submissions for the tenant.
         */
        get: operations["list_submissions_api_mga_submission_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Triage
         * @description Dev/ingestion trigger: run the pipeline for one fixture submission and persist.
         *     (In production the Arq ingestion job invokes the same service.)
         */
        post: operations["run_triage_api_mga_submission_triage_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_mga_submission_triage__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/{submission_id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Act On Submission
         * @description Human action: approve | send (request-info to broker) | escalate.
         */
        post: operations["act_on_submission_api_mga_submission_triage__submission_id__act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Market Matching
         * @description Runs the full pipeline for one submission and enqueues the result for
         *     human review — nothing here binds/sends anything (human-in-the-loop).
         */
        post: operations["run_market_matching_api_es_market_matching_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Market Matching */
        get: operations["list_market_matching_api_es_market_matching_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Matching */
        get: operations["get_market_matching_api_es_market_matching__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description The raw documents `ingest()` persisted via `LocalDocumentStore` for this
         *     submission — real fixture content, not extracted/cited fields (see
         *     core/extraction for that).
         */
        get: operations["list_documents_api_es_market_matching__item_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_es_market_matching__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override */
        post: operations["override_api_es_market_matching__item_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate */
        post: operations["escalate_api_es_market_matching__item_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["send_api_es_market_matching__item_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue */
        post: operations["issue_api_es_market_matching__item_id__issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Package Assembly
         * @description Runs one independent assembly pass per selected carrier (FR-2/FR-4:
         *     never one shared result reused across carriers) and enqueues each as its
         *     own, independently reviewable ReviewItem (FR-18).
         */
        post: operations["run_package_assembly_api_es_package_assembly_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Package Assembly */
        get: operations["list_package_assembly_api_es_package_assembly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package Assembly */
        get: operations["get_package_assembly_api_es_package_assembly__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_es_package_assembly__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly/{item_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit
         * @description FR-20's "Edit" action — logged like any other broker action; the
         *     generic ReviewQueueService has no dedicated "edited" status, so this
         *     records the audit trail (FR-21) without changing ReviewStatus.
         */
        post: operations["edit_api_es_package_assembly__item_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/package-assembly/{item_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Sent
         * @description FR-20's "Mark as sent" — a manual log only; this workflow never
         *     transmits anything automatically (PRD Section 2.2).
         */
        post: operations["mark_sent_api_es_package_assembly__item_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent Communication
         * @description Drafts one communication from a trigger object (PRD FR-1/FR-2: a Market
         *     Matching / Package Assembly output object, or a manually-logged trigger) —
         *     never sends anything (human-in-the-loop, FR-20).
         */
        post: operations["run_agent_communication_api_es_agent_communication_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Communication */
        get: operations["list_agent_communication_api_es_agent_communication_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Communication */
        get: operations["get_agent_communication_api_es_agent_communication__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_es_agent_communication__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["send_api_es_agent_communication__item_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit
         * @description Audit-only, no status change (FR-17 logs the edit for the feedback loop;
         *     computing a real edit-distance needs the FE's submitted edited body, which
         *     is a follow-on enhancement — same simplification package_assembly's own
         *     ``/edit`` made).
         */
        post: operations["edit_api_es_agent_communication__item_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discard
         * @description FR-15's third one-click action. ``ReviewStatus`` has no frozen
         *     "discarded" value, so this sets the workflow-owned ``payload.status``
         *     instead of routing through ``review_queue.act()`` — same pattern as
         *     ``compliance-clear`` below.
         */
        post: operations["discard_api_es_agent_communication__item_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/agent-communication/{item_id}/compliance-clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compliance Clear
         * @description FR-8/FR-16: clears the compliance-review gate on a No Market Found
         *     draft, once the design partner's compliance/legal function has actually
         *     signed off (RA-TN-06 — this endpoint does not decide THAT question, it
         *     only records that a human with authority marked it resolved). Senior/admin
         *     only, mirroring review_queue's existing gating for consequential actions.
         *     ``ReviewAction`` has no "compliance sign-off" value (frozen enum), so this
         *     is a dedicated, router-owned endpoint rather than a ``review_queue.act()``
         *     call — see module docstring.
         */
        post: operations["compliance_clear_api_es_agent_communication__item_id__compliance_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActRequest */
        ActRequest: {
            /** Action */
            action: string;
            /** Amount */
            amount?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ActivityEntry */
        ActivityEntry: {
            /** At */
            at: string;
            /** Who */
            who: string;
            /** What */
            what: string;
            /** Ctx */
            ctx?: string | null;
            /** Conf */
            conf?: string | null;
        };
        /** AppetiteResultOut */
        AppetiteResultOut: {
            /** Rule */
            rule: string;
            /** Pass */
            pass: boolean;
            /** Hard */
            hard: boolean;
            /** Detail */
            detail: string;
        };
        /** BlockingItemOut */
        BlockingItemOut: {
            /** Item */
            item: string;
            /** Reason */
            reason: string;
        };
        /** CarrierMatchOut */
        CarrierMatchOut: {
            /** Carrier Id */
            carrier_id: string;
            /** Carrier Name */
            carrier_name: string;
            /** Score */
            score: number;
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Flags
             * @default []
             */
            flags: string[];
        };
        /** ConsistencyCheck */
        ConsistencyCheck: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Status */
            status: string;
        };
        /** CoverLetterCitationOut */
        CoverLetterCitationOut: {
            /** Claim */
            claim: string;
            /** Source */
            source: string;
        };
        /** CoverLetterOut */
        CoverLetterOut: {
            /** Body */
            body: string;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["CoverLetterCitationOut"][];
        };
        /** DiligentSearchOut */
        DiligentSearchOut: {
            /** Required */
            required: boolean;
            /** On File */
            on_file: number;
            /** Compliant */
            compliant: boolean;
            /** Note */
            note: string;
        };
        /** DocChecklistItemOut */
        DocChecklistItemOut: {
            /** Document Type */
            document_type: string;
            /** Included */
            included: boolean;
            /** Source */
            source?: string | null;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Filename */
            filename: string;
            /** Kind */
            kind: string;
            /** Content */
            content: string;
        };
        /**
         * DraftCommunicationOut
         * @description The FE review-queue screen's data needs for one drafted communication.
         */
        DraftCommunicationOut: {
            /** Draft Id */
            draft_id: string;
            /** Trigger Type */
            trigger_type: string;
            /** Source Workflow */
            source_workflow: string;
            /** Source Record Id */
            source_record_id?: string | null;
            /** Submission Id */
            submission_id?: string | null;
            /** Named Insured */
            named_insured?: string | null;
            /** Carrier Name */
            carrier_name?: string | null;
            /** Retail Agent Name */
            retail_agent_name?: string | null;
            /** Retail Agency */
            retail_agency?: string | null;
            /** Subject Line */
            subject_line: string;
            /** Body */
            body: string;
            /**
             * Requires Compliance Review
             * @default false
             */
            requires_compliance_review: boolean;
            /**
             * Carrier Names Disclosed
             * @default false
             */
            carrier_names_disclosed: boolean;
            /**
             * Grounding Citations
             * @default []
             */
            grounding_citations: components["schemas"]["GroundingCitationOut"][];
            /**
             * Status
             * @default DRAFT
             */
            status: string;
            /** Edit Distance From Original */
            edit_distance_from_original?: number | null;
            /** Generated Timestamp */
            generated_timestamp: string;
            /** Sent Timestamp */
            sent_timestamp?: string | null;
        };
        /** ExcludedCarrierOut */
        ExcludedCarrierOut: {
            /** Carrier Id */
            carrier_id: string;
            /** Carrier Name */
            carrier_name: string;
            /** Rule */
            rule: string;
            /** Reason */
            reason: string;
        };
        /** ExtractedFieldOut */
        ExtractedFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string | null;
            /** Required */
            required: boolean;
            /** Confidence */
            confidence: number;
            /** Source */
            source?: string | null;
        };
        /** GapItemOut */
        GapItemOut: {
            /** Item */
            item: string;
            /**
             * Cover Letter Acknowledgment
             * @default true
             */
            cover_letter_acknowledgment: boolean;
        };
        /**
         * GroundingCitationOut
         * @description A lighter-weight grounding note than the frozen ``Citation`` DTO (which
         *     requires a document kind/filename) — this workflow's facts come from an
         *     upstream structured object, not a scanned document, so citations point at
         *     the source FIELD instead.
         */
        GroundingCitationOut: {
            /** Claim */
            claim: string;
            /** Source Field */
            source_field: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LossMetrics */
        LossMetrics: {
            /** Totalincurred */
            totalIncurred: string;
            /** Totalpaid */
            totalPaid: string;
            /** Openclaims */
            openClaims: number;
            /** Years */
            years: number;
            /** Required */
            required: number;
            /** Trend */
            trend: string;
        };
        /**
         * MarketMatchingPayload
         * @description The FE Market Matching screen's data needs: a ranked panel, what got
         *     excluded and why, and the independent compliance flag.
         */
        MarketMatchingPayload: {
            /** Submission Id */
            submission_id: string | null;
            /**
             * Matches
             * @default []
             */
            matches: components["schemas"]["CarrierMatchOut"][];
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["ExcludedCarrierOut"][];
            diligent_search: components["schemas"]["DiligentSearchOut"];
        };
        /** MissingItem */
        MissingItem: {
            /** Item */
            item: string;
            /** Reason */
            reason: string;
            /** Severity */
            severity: string;
        };
        /**
         * PackageAssemblyPayload
         * @description The FE Package Assembly screen's data needs — one per carrier package,
         *     even within a multi-carrier simultaneous selection (FR-18).
         */
        PackageAssemblyPayload: {
            /** Package Id */
            package_id: string;
            /** Submission Id */
            submission_id: string | null;
            /** Carrier Id */
            carrier_id: string;
            /** Carrier Name */
            carrier_name: string;
            /** Status */
            status: string;
            /**
             * Document Checklist
             * @default []
             */
            document_checklist: components["schemas"]["DocChecklistItemOut"][];
            /**
             * Supplemental Form Fields
             * @default []
             */
            supplemental_form_fields: components["schemas"]["SupplementalFieldOut"][];
            /**
             * Diligent Search Attached
             * @default false
             */
            diligent_search_attached: boolean;
            cover_letter: components["schemas"]["CoverLetterOut"];
            /**
             * Blocking Items
             * @default []
             */
            blocking_items: components["schemas"]["BlockingItemOut"][];
            /**
             * Gap Items Disclosed
             * @default []
             */
            gap_items_disclosed: components["schemas"]["GapItemOut"][];
            /**
             * Status Log
             * @default []
             */
            status_log: components["schemas"]["StatusLogEntryOut"][];
        };
        /** RiskFactor */
        RiskFactor: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Weight */
            weight: number;
        };
        /** StatusLogEntryOut */
        StatusLogEntryOut: {
            /** Action */
            action: string;
            /** Timestamp */
            timestamp: string;
            /** User */
            user: string;
        };
        /**
         * SubmissionRow
         * @description Inbox/list row — the MGA-FE ``Submission`` shape.
         */
        SubmissionRow: {
            /** Id */
            id: string;
            /** Insured */
            insured: string;
            /** Industry */
            industry: string;
            /** State */
            state: string;
            /** Tiv */
            tiv: string;
            /** Premium */
            premium: string;
            /** Score */
            score: number | null;
            /** Appetite */
            appetite: string;
            /** Recommendation */
            recommendation: string;
            /** Status */
            status: string;
            /** Received */
            received: string;
        };
        /** SupplementalFieldOut */
        SupplementalFieldOut: {
            /** Field Name */
            field_name: string;
            /** Value */
            value?: string | null;
            /**
             * Auto Filled
             * @default false
             */
            auto_filled: boolean;
            /** Source Citation */
            source_citation?: string | null;
        };
        /** TriageDetail */
        TriageDetail: {
            /** Recommendation */
            recommendation: string;
            /** Confidence */
            confidence: number;
            /** Hardrulepassed */
            hardRulePassed: boolean;
            /** Failedrules */
            failedRules: string[];
            /** Processing */
            processing: string;
            /** Rulesversion */
            rulesVersion: string;
            meta: components["schemas"]["TriageMeta"];
            /** Docs */
            docs: components["schemas"]["TriageDoc"][];
            /** Fields */
            fields: components["schemas"]["ExtractedFieldOut"][];
            loss: components["schemas"]["LossMetrics"];
            /** Consistency */
            consistency: components["schemas"]["ConsistencyCheck"][];
            /** Missinginfo */
            missingInfo: components["schemas"]["MissingItem"][];
            /** Factors */
            factors: components["schemas"]["RiskFactor"][];
            /** Narrative */
            narrative: string;
            /** Citations */
            citations: string[];
            /** Appetite */
            appetite: components["schemas"]["AppetiteResultOut"][];
            /** Activity */
            activity: components["schemas"]["ActivityEntry"][];
        };
        /** TriageDoc */
        TriageDoc: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Pages */
            pages: number;
            /** Fields */
            fields: number;
            /** Confidence */
            confidence: number;
            /** Classified */
            classified: boolean;
        };
        /** TriageMeta */
        TriageMeta: {
            /** Received */
            received: string[];
            /** Lowconfidence */
            lowConfidence: string[];
            /** Timestamp */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ReviewItemOut */
        verticals__es__workflows__agent_communication__router__ReviewItemOut: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id: string | null;
            /** Status */
            status: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            payload?: components["schemas"]["DraftCommunicationOut"] | null;
        };
        /** RunRequest */
        verticals__es__workflows__agent_communication__router__RunRequest: {
            /** Trigger */
            trigger: {
                [key: string]: unknown;
            };
        };
        /** ReviewItemOut */
        verticals__es__workflows__market_matching__router__ReviewItemOut: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id: string | null;
            /** Status */
            status: string;
            payload?: components["schemas"]["MarketMatchingPayload"] | null;
        };
        /** RunRequest */
        verticals__es__workflows__market_matching__router__RunRequest: {
            /** Submission Ref */
            submission_ref: string;
        };
        /** ReviewItemOut */
        verticals__es__workflows__package_assembly__router__ReviewItemOut: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id: string | null;
            /** Carrier Id */
            carrier_id?: string | null;
            /** Status */
            status: string;
            payload?: components["schemas"]["PackageAssemblyPayload"] | null;
        };
        /** RunRequest */
        verticals__es__workflows__package_assembly__router__RunRequest: {
            /** Scenario Ref */
            scenario_ref: string;
            /** Carrier Id */
            carrier_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_core_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    list_submissions_api_mga_submission_triage_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_triage_api_mga_submission_triage_run_post: {
        parameters: {
            query: {
                message_id: string;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_mga_submission_triage__submission_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    act_on_submission_api_mga_submission_triage__submission_id__act_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_market_matching_api_es_market_matching_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_market_matching_api_es_market_matching_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_matching_api_es_market_matching__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_es_market_matching__item_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_es_market_matching__item_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_api_es_market_matching__item_id__override_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_api_es_market_matching__item_id__escalate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_es_market_matching__item_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_es_market_matching__item_id__issue_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__market_matching__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_package_assembly_api_es_package_assembly_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_package_assembly_api_es_package_assembly_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_assembly_api_es_package_assembly__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_es_package_assembly__item_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_es_package_assembly__item_id__edit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_sent_api_es_package_assembly__item_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__package_assembly__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_communication_api_es_agent_communication_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_communication_api_es_agent_communication_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_communication_api_es_agent_communication__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_es_agent_communication__item_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_es_agent_communication__item_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_es_agent_communication__item_id__edit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_api_es_agent_communication__item_id__discard_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compliance_clear_api_es_agent_communication__item_id__compliance_clear_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verticals__es__workflows__agent_communication__router__ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
