/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/core/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Phase marker confirms which milestone this build is at.
         */
        get: operations["health_api_core_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submissions
         * @description Inbox — triaged submissions for the tenant.
         */
        get: operations["list_submissions_api_mga_submission_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Triage
         * @description Dev/ingestion trigger: run the pipeline for one fixture submission and persist.
         *     (In production the Arq ingestion job invokes the same service.)
         */
        post: operations["run_triage_api_mga_submission_triage_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_mga_submission_triage__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mga/submission-triage/{submission_id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Act On Submission
         * @description Human action: approve | send (request-info to broker) | escalate.
         */
        post: operations["act_on_submission_api_mga_submission_triage__submission_id__act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Market Matching
         * @description Runs the full pipeline for one submission and enqueues the result for
         *     human review — nothing here binds/sends anything (human-in-the-loop).
         */
        post: operations["run_market_matching_api_es_market_matching_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Market Matching */
        get: operations["list_market_matching_api_es_market_matching_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Matching */
        get: operations["get_market_matching_api_es_market_matching__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_es_market_matching__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override */
        post: operations["override_api_es_market_matching__item_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate */
        post: operations["escalate_api_es_market_matching__item_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["send_api_es_market_matching__item_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/es/market-matching/{item_id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue */
        post: operations["issue_api_es_market_matching__item_id__issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActRequest */
        ActRequest: {
            /** Action */
            action: string;
            /** Amount */
            amount?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ActivityEntry */
        ActivityEntry: {
            /** At */
            at: string;
            /** Who */
            who: string;
            /** What */
            what: string;
            /** Ctx */
            ctx?: string | null;
            /** Conf */
            conf?: string | null;
        };
        /** AppetiteResultOut */
        AppetiteResultOut: {
            /** Rule */
            rule: string;
            /** Pass */
            pass: boolean;
            /** Hard */
            hard: boolean;
            /** Detail */
            detail: string;
        };
        /** CarrierMatchOut */
        CarrierMatchOut: {
            /** Carrier Id */
            carrier_id: string;
            /** Carrier Name */
            carrier_name: string;
            /** Score */
            score: number;
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Flags
             * @default []
             */
            flags: string[];
        };
        /** ConsistencyCheck */
        ConsistencyCheck: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Status */
            status: string;
        };
        /** DiligentSearchOut */
        DiligentSearchOut: {
            /** Required */
            required: boolean;
            /** On File */
            on_file: number;
            /** Compliant */
            compliant: boolean;
            /** Note */
            note: string;
        };
        /** ExcludedCarrierOut */
        ExcludedCarrierOut: {
            /** Carrier Id */
            carrier_id: string;
            /** Carrier Name */
            carrier_name: string;
            /** Rule */
            rule: string;
            /** Reason */
            reason: string;
        };
        /** ExtractedFieldOut */
        ExtractedFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string | null;
            /** Required */
            required: boolean;
            /** Confidence */
            confidence: number;
            /** Source */
            source?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LossMetrics */
        LossMetrics: {
            /** Totalincurred */
            totalIncurred: string;
            /** Totalpaid */
            totalPaid: string;
            /** Openclaims */
            openClaims: number;
            /** Years */
            years: number;
            /** Required */
            required: number;
            /** Trend */
            trend: string;
        };
        /**
         * MarketMatchingPayload
         * @description The FE Market Matching screen's data needs: a ranked panel, what got
         *     excluded and why, and the independent compliance flag.
         */
        MarketMatchingPayload: {
            /** Submission Id */
            submission_id: string | null;
            /**
             * Matches
             * @default []
             */
            matches: components["schemas"]["CarrierMatchOut"][];
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["ExcludedCarrierOut"][];
            diligent_search: components["schemas"]["DiligentSearchOut"];
        };
        /** MissingItem */
        MissingItem: {
            /** Item */
            item: string;
            /** Reason */
            reason: string;
            /** Severity */
            severity: string;
        };
        /** ReviewItemOut */
        ReviewItemOut: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id: string | null;
            /** Status */
            status: string;
            payload?: components["schemas"]["MarketMatchingPayload"] | null;
        };
        /** RiskFactor */
        RiskFactor: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Weight */
            weight: number;
        };
        /** RunRequest */
        RunRequest: {
            /** Submission Ref */
            submission_ref: string;
        };
        /**
         * SubmissionRow
         * @description Inbox/list row — the MGA-FE ``Submission`` shape.
         */
        SubmissionRow: {
            /** Id */
            id: string;
            /** Insured */
            insured: string;
            /** Industry */
            industry: string;
            /** State */
            state: string;
            /** Tiv */
            tiv: string;
            /** Premium */
            premium: string;
            /** Score */
            score: number | null;
            /** Appetite */
            appetite: string;
            /** Recommendation */
            recommendation: string;
            /** Status */
            status: string;
            /** Received */
            received: string;
        };
        /** TriageDetail */
        TriageDetail: {
            /** Recommendation */
            recommendation: string;
            /** Confidence */
            confidence: number;
            /** Hardrulepassed */
            hardRulePassed: boolean;
            /** Failedrules */
            failedRules: string[];
            /** Processing */
            processing: string;
            /** Rulesversion */
            rulesVersion: string;
            meta: components["schemas"]["TriageMeta"];
            /** Docs */
            docs: components["schemas"]["TriageDoc"][];
            /** Fields */
            fields: components["schemas"]["ExtractedFieldOut"][];
            loss: components["schemas"]["LossMetrics"];
            /** Consistency */
            consistency: components["schemas"]["ConsistencyCheck"][];
            /** Missinginfo */
            missingInfo: components["schemas"]["MissingItem"][];
            /** Factors */
            factors: components["schemas"]["RiskFactor"][];
            /** Narrative */
            narrative: string;
            /** Citations */
            citations: string[];
            /** Appetite */
            appetite: components["schemas"]["AppetiteResultOut"][];
            /** Activity */
            activity: components["schemas"]["ActivityEntry"][];
        };
        /** TriageDoc */
        TriageDoc: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Pages */
            pages: number;
            /** Fields */
            fields: number;
            /** Confidence */
            confidence: number;
            /** Classified */
            classified: boolean;
        };
        /** TriageMeta */
        TriageMeta: {
            /** Received */
            received: string[];
            /** Lowconfidence */
            lowConfidence: string[];
            /** Timestamp */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_core_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    list_submissions_api_mga_submission_triage_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_triage_api_mga_submission_triage_run_post: {
        parameters: {
            query: {
                message_id: string;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_mga_submission_triage__submission_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    act_on_submission_api_mga_submission_triage__submission_id__act_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_market_matching_api_es_market_matching_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_market_matching_api_es_market_matching_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_matching_api_es_market_matching__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_es_market_matching__item_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_api_es_market_matching__item_id__override_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_api_es_market_matching__item_id__escalate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_es_market_matching__item_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_es_market_matching__item_id__issue_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
                "x-role"?: string | null;
                "x-vertical"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
